name: Bug Report
description: File a bug report
labels: ["bug", "triage"]
assignees:
  - octocat

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Check those before continue
      options:
        - label: I checked the documentation and found no answer
        - label: I checked to make sure that this issue has not been filed yet
        - label: I am running the latest stable version of the code
        - label: I have the correct environment and set-up needed for running the code

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the issue here.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### Detailed information, fill it where possible / applicable
        ___

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant application logs
      description: Add relevant log excerpt for the application, if applicable.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ### OS / environment information, fill it where possible / applicable
        ___

  - type: dropdown
    id: operating-systems
    attributes:
      label: What type of Operating System are you seeing the problem on?
      multiple: true
      options:
        - Linux
        - Windows
        - Mac
        - Other
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        examples:
          - **OS**: Ubuntu 20.04
          - **Compiler/interpreter version**: Python 3.10.2
      value: |
        - OS:
        - Compiler/interpreter version:
      render: Markdown
    validations:
      required: false
